Update to Upstream V0.27.0
Groestlcoin/rust-groestlcoin pull request #1
Opened 2022-02-05 01:48 UTC by HashEngineering

2022-02-05 16:57 UTC, gruve-p requested changes
22 failing tests left

2022-02-05 16:57 UTC, gruve-p commented on contrib/test.sh
> +  cargo run --no-default-features --features no-std --example bip32 L1HKVVLHXiUhecWnwFYF6L3shkf1E12HUmuZTESvBXUdx3yqVP1D
These WIF addresses needs to be fixed

2022-02-05 16:57 UTC, gruve-p commented on embedded/README.md
> +Address: bc1qpx9t9pzzl4qsydmhyt6ctrxxjd4ep549np9993
Wif address and address needs fixing

2022-02-05 16:57 UTC, gruve-p commented on embedded/src/main.rs
> +    let raw = "L1HKVVLHXiUhecWnwFYF6L3shkf1E12HUmuZTESvBXUdx3yqVP1D";
WIF address needs fixing

2022-02-05 16:57 UTC, gruve-p commented on embedded/src/main.rs
> +    assert_eq!(address.to_string(), "bc1qpx9t9pzzl4qsydmhyt6ctrxxjd4ep549np9993".to_string());
Address needs fixing

2022-02-05 16:57 UTC, gruve-p commented on examples/bip32.rs
> +    // cargo run --example bip32 L1HKVVLHXiUhecWnwFYF6L3shkf1E12HUmuZTESvBXUdx3yqVP1D
Example WIF needs fixing

2022-02-05 16:57 UTC, gruve-p commented on src/util/address.rs
> +            ("bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqzk5jj0", "512079be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798")
these are bitcoin addresses

2022-02-05 16:57 UTC, gruve-p commented on src/util/address.rs
> +            "bc1gmk9yu",
these are bitcoin addresses

2022-02-05 16:57 UTC, gruve-p commented on src/util/address.rs
> +            "bc1zw508d6qejxtdg4y5r3zarvaryvg6kdaj",
these are bitcoin addresses

2022-02-05 16:57 UTC, gruve-p commented on src/util/address.rs
> +        for el in  ["132F25rTsvBdp9JzLLBHP5mvGY66i1xdiM", "33iFwdLuRpW1uK1RTRqsoi8rR4NpDzk66k"].iter() {
these are bitcoin addresses

2022-02-05 16:57 UTC, gruve-p commented on src/util/base58.rs
>          assert_eq!(&check_encode_slice(&addr[..]), "1PfJpZsjreyVrqeoAfabrRwwjQyoSQMmHH");
`1PfJpZsjreyVrqeoAfabrRwwjQyoSQMmHH` is a bitcoin address

2022-02-05 16:57 UTC, gruve-p commented on src/util/ecdsa.rs
> +        assert_eq!(&sk.to_wif(), "5JYkZjmN7PVMjJUfJWfRFwtuXTGB439XV6faajeHPAM9Z2PT2R3");
These are either bitcoin wif keys or bitcoin addresses

2022-02-05 16:57 UTC, gruve-p commented on src/util/ecdsa.rs
> +        assert_eq!(&addr.to_string(), "1GhQvF6dL8xa6wBxLnWmHcQsurx9RxiMc8");
this is a bitcoin address

2022-02-05 16:57 UTC, gruve-p commented on src/util/ecdsa.rs
> +        static KEY_WIF: &'static str = "cVt4o7BGAig1UXywgGSmARhxMdzP5qvQsxKkSsc1XEkw3tDTQFpy";
bitcoin private key

2022-02-05 17:00 UTC, gruve-p commented on src/util/address.rs
> +        for el in ["bcrt1q2nfxmhd4n3c8834pj72xagvyr9gl57n5r94fsl", "grs1qwqdg6squsna38e46795at95yu9atm8azzmyvckulcc7kytlcckxsphnwkk"].iter() {
`bcrt1q2nfxmhd4n3c8834pj72xagvyr9gl57n5r94fsl` is bitcoin address

2022-02-05 19:29 UTC, HashEngineering commented on src/consensus/params.rs
> +    0x00ffffffffffffffu64,
This is the number in `SigNetParams`
`00000377ae000000000000000000000000000000000000000000000000000000`

2022-02-05 19:29 UTC, HashEngineering commented on src/consensus/params.rs
> +    0x00ffffffffffffffu64,
`00ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff` is RegTest

2022-02-05 19:35 UTC, HashEngineering commented on src/consensus/params.rs
> +    0x00ffffffffffffffu64,
Nevermind, looking at the wrong code.

2022-02-07 08:43 UTC, gruve-p commented on contrib/test.sh
> +  cargo run --no-default-features --features no-std --example bip32 L1HKVVLHXiUhecWnwFYF6L3shkf1E12HUmuZTESvBXUdx3yqVP1D
Fixed

2022-02-07 08:44 UTC, gruve-p commented on embedded/README.md
> +Address: bc1qpx9t9pzzl4qsydmhyt6ctrxxjd4ep549np9993
Fixed

2022-02-07 08:45 UTC, gruve-p commented on embedded/src/main.rs
> +    let raw = "L1HKVVLHXiUhecWnwFYF6L3shkf1E12HUmuZTESvBXUdx3yqVP1D";
fixed

2022-02-07 08:46 UTC, gruve-p commented on embedded/src/main.rs
> +    assert_eq!(address.to_string(), "bc1qpx9t9pzzl4qsydmhyt6ctrxxjd4ep549np9993".to_string());
fixed

2022-02-07 08:47 UTC, gruve-p commented on examples/bip32.rs
> +    // cargo run --example bip32 L1HKVVLHXiUhecWnwFYF6L3shkf1E12HUmuZTESvBXUdx3yqVP1D
fixed

2022-02-07 08:55 UTC, gruve-p commented on src/util/address.rs
> +        for el in  ["132F25rTsvBdp9JzLLBHP5mvGY66i1xdiM", "33iFwdLuRpW1uK1RTRqsoi8rR4NpDzk66k"].iter() {
fixed

2022-02-07 08:57 UTC, gruve-p commented on src/util/base58.rs
>          assert_eq!(&check_encode_slice(&addr[..]), "1PfJpZsjreyVrqeoAfabrRwwjQyoSQMmHH");
fixed

2022-02-07 08:57 UTC, gruve-p commented on src/util/ecdsa.rs
> +        assert_eq!(&sk.to_wif(), "5JYkZjmN7PVMjJUfJWfRFwtuXTGB439XV6faajeHPAM9Z2PT2R3");
fixed

2022-02-07 08:58 UTC, gruve-p commented on src/util/ecdsa.rs
> +        assert_eq!(&addr.to_string(), "1GhQvF6dL8xa6wBxLnWmHcQsurx9RxiMc8");
fixed

2022-02-07 08:58 UTC, gruve-p commented on src/util/ecdsa.rs
> +        static KEY_WIF: &'static str = "cVt4o7BGAig1UXywgGSmARhxMdzP5qvQsxKkSsc1XEkw3tDTQFpy";
fixed

2022-02-07 09:02 UTC, gruve-p commented on src/util/address.rs
> +        for el in ["bcrt1q2nfxmhd4n3c8834pj72xagvyr9gl57n5r94fsl", "grs1qwqdg6squsna38e46795at95yu9atm8azzmyvckulcc7kytlcckxsphnwkk"].iter() {
fixed

2022-02-12 23:26 UTC, gruve-p approved these changes

2022-02-12 23:30 UTC, merged